export enum AppTabs {
  TIER_LIST = 'TIER_LIST',
  MEAL_REGISTRATION = 'MEAL_REGISTRATION',
  STATS_AND_PREV_MEALS = 'STATS_AND_PREV_MEALS',
  MANAGEMENT = 'MANAGEMENT',
  TIER_LIST_RANK = 'TIER_LIST_MAKER',
  TIER_LIST_CREATE = 'TIER_LIST_CREATE',
}
